contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://erwinsteffens.com/"
languageCode = "en-us"
title = "Erwin Steffens"
theme = "blog-theme"
paginate = 10

[author]
 	name = "Erwin Steffens"

[params]
    highlight = "github"
    showCategories = false
    tagline = "Software developer interested in creating scalable applications based on microservices and docker"
    home = "Home"
    disqusShortname = "erwinsteffens"
    googleAuthorship = "116367618088685172564"
    googleAnalytics = "UA-71230170-1"
    gravatarHash = "bb982f60f7ce4de442b37f496730d3fd"
    github = "https://github.com/erwinsteffens/"
    linkedin = "https://linkedin.com/in/erwinsteffens"
    googleplus = "https://plus.google.com/116367618088685172564/po"
    twitter = "https://twitter.com/erwinsteffens"
    rss = false