contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true
baseurl = "http://erwinsteffens.com/"
languageCode = "en-us"
title = "Erwin Steffens"
theme = "blog-theme"

[params]
	description = "Software developer interested in creating scalable applications based on microservices and docker"
	google_analytics = "UA-71230170-1"
	disqusShortname = "erwinsteffens"
		
[params.social]
	github      	= "erwinsteffens"
	twitter     	= "erwinsteffens"
	googleplus      = "erwinsteffens"
	linkedin        = "erwinsteffens"